name: Build, Release and Publish

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: write

jobs:
  # Build the project and capture the build artifacts
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: get version name
        id: semver
        run: echo ::set-output name=version::$(grep mod_version gradle.properties | cut -d= -f2)

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build -Pbuild.release=true

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lapismyzuli-release-artifacts-${{ steps.semver.outputs.version }}
          path: build/libs/

  # Create a GitHub release and upload the build artifacts
  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: get version name
        id: semver
        run: echo ::set-output name=version::$(grep mod_version gradle.properties | cut -d= -f2)

      - name: download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lapismyzuli-release-artifacts-${{ steps.semver.outputs.version }}

      - name: create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_PERSONAL }}
          tag: v${{ steps.semver.outputs.version }}
          name: Release v${{ steps.semver.outputs.version }}
          generateReleaseNotes: true
          draft: false
          prerelease: false
          artifacts: lapismyzuli-${{ steps.semver.outputs.version }}.jar

  # Publish the release to Modrinth
  publish:
    name: publish
    needs: release
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: get version name
        id: semver
        run: echo ::set-output name=version::$(grep mod_version gradle.properties | cut -d= -f2)

      - name: download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lapismyzuli-release-artifacts-${{ steps.semver.outputs.version }}

      - name: publish release to modrinth
        uses: cloudnode-pro/modrinth-publish@2.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: WbIOf2fM
          name: ${{ steps.semver.outputs.version }}
          version: ${{ steps.semver.outputs.version }}
          loaders: |-
            fabric
          game-versions: |-
            1.21.4
          files: build/libs/lapismyzuli-${{ steps.semver.outputs.version }}.jar