name: Build, Release and Publish

on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  # Build the project and capture the build artifacts
  build:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.semver.outputs.version }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: get version name
        id: semver
        run: echo "version=$(grep mod_version gradle.properties | cut -d= -f2)" >> $GITHUB_OUTPUT

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build -Pbuild.release=true

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lapismyzuli-release-artifacts-${{ steps.semver.outputs.version }}
          path: build/libs/

  # Create a GitHub release and upload the build artifacts
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lapismyzuli-release-artifacts-${{ needs.build.outputs.version }}

      - name: create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ needs.build.outputs.version }}
          name: Release v${{ needs.build.outputs.version }}
          generateReleaseNotes: true
          draft: false
          prerelease: false
          artifacts: lapismyzuli-${{ needs.build.outputs.version }}.jar

  # Publish the release to Modrinth
  publish-to-modrinth:
    runs-on: ubuntu-22.04
    needs: release
    steps:
    - name: download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: lapismyzuli-release-artifacts-${{ needs.build.outputs.version }}

    - name: publish release to modrinth
      uses: cloudnode-pro/modrinth-publish@2.0.0
      with:
        token: ${{ secrets.MODRINTH_TOKEN }}
        project: WbIOf2fM
        name: ${{ needs.build.outputs.version }}
        version: ${{ needs.build.outputs.version }}
        changelog: |-
          See the [GitHub Release Notes](https://github.com/Priddlesaur/LapisMyZuli/releases/tag/v${{ needs.build.outputs.version }}) for the full changelog.
        loaders: |-
          fabric
        game-versions: |-
          1.21.4
        files: lapismyzuli-${{ needs.build.outputs.version }}.jar
