name: Publish

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lapismyzuli-release-artifacts-${{ github.event.release.tag_name }}

      - name: publish release to modrinth
        uses: cloudnode-pro/modrinth-publish@2.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: WbIOf2fM
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: |-
            fabric
          game-versions: |-
            1.21.4
          files: build/libs/lapismyzuli-${{ github.event.release.tag_name }}.jar
